[google]
client_id = "614110627327-9ap4vkf06d0moqt83snj1lg6ivilfiu3.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://your-deployed-app-url/oauth_callback"

[github]
client_id = "Ov23li2L2zUtFxmsZHkA"
client_secret = "2ce9d66ec5ec4b0b0009f8167e576b25276c67c0"
redirect_uri = "https://your-deployed-app-url/oauth_callback"
